name: Sync to GitLab

on:
  push:
    branches:
      - main # Đổi thành nhánh bạn muốn đồng bộ (ví dụ: master)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/binz0209/canpanycpgl.git
          git push gitlab main --force
